package gui;

import dblis.GraphInfo;
import dblis.SportData2;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;

/**
 *
 * @author Chen
 */
public class MainFrame extends CenterFrame {
    
    private FXPanel fxPanel;
    DefaultListModel candidateListModel = new DefaultListModel();
    DefaultListModel eventListModel = new DefaultListModel();

    /**
     * Creates new form MainFrame
     */
    List<JCheckBox> sportCheckboxes;
    
    public MainFrame() {
        initComponents();
        centerize();
        sportCheckboxes = new ArrayList<>();
        sportCheckboxes.add(hockeyCheckBox);
        sportCheckboxes.add(tennisCheckBox);
        sportCheckboxes.add(footballCheckBox);
        sportCheckboxes.add(cyclingCheckBox);
        sportCheckboxes.add(skatingCheckBox);
        fxPanel = new FXPanel();
        testPanel.add(fxPanel);
//        GraphInfo graphInfo = new GraphInfo(startTimePicker.getDate(),
//                endTimePicker.getDate(), footballCheckBox.isSelected(),
//            hockeyCheckBox.isSelected(), cyclingCheckBox.isSelected(),
//            tennisCheckBox.isSelected(), skatingCheckBox.isSelected(), 1);
        fxPanel.drawScene(0);
        eventList.setModel(eventListModel);
        candidateList.setModel(candidateListModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sportsDialog = new javax.swing.JDialog();
        footballCheckBox = new javax.swing.JCheckBox();
        hockeyCheckBox = new javax.swing.JCheckBox();
        cyclingCheckBox = new javax.swing.JCheckBox();
        tennisCheckBox = new javax.swing.JCheckBox();
        skatingCheckBox = new javax.swing.JCheckBox();
        sportsSelectAllBtn = new javax.swing.JButton();
        sportsDeselectAllBtn = new javax.swing.JButton();
        sportsInverseSelectionBtn = new javax.swing.JButton();
        sportsOKBtn = new javax.swing.JButton();
        sportsCancelBtn = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        timeIntervalLabel = new javax.swing.JLabel();
        startTimePicker = new com.lavantech.gui.comp.DateTimePicker();
        endTimePicker = new com.lavantech.gui.comp.DateTimePicker();
        startTimeLabel = new javax.swing.JLabel();
        endTimeLabel = new javax.swing.JLabel();
        timeIntervalCombo = new javax.swing.JComboBox();
        sportsLabel = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox();
        yearLabel = new javax.swing.JLabel();
        sportsChooseBtn = new javax.swing.JButton();
        showYearDataCheckbox = new javax.swing.JCheckBox();
        showBtn = new javax.swing.JButton();
        lineChartBtn = new javax.swing.JButton();
        histogramBtn = new javax.swing.JButton();
        pieChartBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        visualizationPanel = new javax.swing.JPanel();
        testPanel = new javax.swing.JPanel();
        comparisonPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        candidateList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList();
        sportComboBox = new javax.swing.JComboBox();
        typeComboBox = new javax.swing.JComboBox();
        typeLabel = new javax.swing.JLabel();
        sportLabel2 = new javax.swing.JLabel();
        eventsLabel = new javax.swing.JLabel();
        Candidates = new javax.swing.JLabel();
        addEventBtn = new javax.swing.JButton();
        teamALabel = new javax.swing.JLabel();
        teamBComboBox = new javax.swing.JComboBox();
        teamAComboBox = new javax.swing.JComboBox();
        teamBLabel = new javax.swing.JLabel();
        showComparisonBtn = new javax.swing.JButton();
        clearCandidateBtn = new javax.swing.JButton();
        showComparisonBtn1 = new javax.swing.JButton();
        deleteOneBtn = new javax.swing.JButton();
        addTeamBtn = new javax.swing.JButton();

        sportsDialog.setTitle("Select the sports to show");

        footballCheckBox.setText("Football");

        hockeyCheckBox.setText("Hockey");
        hockeyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hockeyCheckBoxActionPerformed(evt);
            }
        });

        cyclingCheckBox.setText("Cycling");

        tennisCheckBox.setText("Tennis");

        skatingCheckBox.setText("Skating");

        sportsSelectAllBtn.setText("Select all");
        sportsSelectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsSelectAllBtnActionPerformed(evt);
            }
        });

        sportsDeselectAllBtn.setText("Deselect all");
        sportsDeselectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsDeselectAllBtnActionPerformed(evt);
            }
        });

        sportsInverseSelectionBtn.setText("Invert selection");
        sportsInverseSelectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsInverseSelectionBtnActionPerformed(evt);
            }
        });

        sportsOKBtn.setText("OK");
        sportsOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsOKBtnActionPerformed(evt);
            }
        });

        sportsCancelBtn.setText("Cancel");
        sportsCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sportsDialogLayout = new javax.swing.GroupLayout(sportsDialog.getContentPane());
        sportsDialog.getContentPane().setLayout(sportsDialogLayout);
        sportsDialogLayout.setHorizontalGroup(
            sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sportsDialogLayout.createSequentialGroup()
                        .addComponent(footballCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hockeyCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyclingCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tennisCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skatingCheckBox))
                    .addGroup(sportsDialogLayout.createSequentialGroup()
                        .addComponent(sportsSelectAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sportsDeselectAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sportsInverseSelectionBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sportsOKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sportsCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sportsDialogLayout.setVerticalGroup(
            sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footballCheckBox)
                    .addComponent(hockeyCheckBox)
                    .addComponent(cyclingCheckBox)
                    .addComponent(tennisCheckBox)
                    .addComponent(skatingCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sportsDeselectAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(sportsSelectAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sportsInverseSelectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportsOKBtn)
                    .addComponent(sportsCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("That bird is fit");

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        timeIntervalLabel.setText("Time interval");

        startTimeLabel.setText("Start time");

        endTimeLabel.setText("End time");

        timeIntervalCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Week", "Day" }));

        sportsLabel.setText("Sports");

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "< -- >", "2013", "2014", "2015", "" }));
        yearCombo.setEnabled(false);

        yearLabel.setText("Year :");
        yearLabel.setEnabled(false);

        sportsChooseBtn.setText("Choose");
        sportsChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsChooseBtnActionPerformed(evt);
            }
        });

        showYearDataCheckbox.setLabel("Show data in one year");
        showYearDataCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearDataCheckboxChanged(evt);
            }
        });
        showYearDataCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showYearDataCheckboxActionPerformed(evt);
            }
        });

        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        lineChartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Data-Line-Chart-icon_32x32.png"))); // NOI18N
        lineChartBtn.setToolTipText("");
        lineChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineChartBtnActionPerformed(evt);
            }
        });

        histogramBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/bar_chart-512_32x32.png"))); // NOI18N
        histogramBtn.setToolTipText("");
        histogramBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramBtnActionPerformed(evt);
            }
        });

        pieChartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/chart_pie_32x32.png"))); // NOI18N
        pieChartBtn.setToolTipText("");
        pieChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieChartBtnActionPerformed(evt);
            }
        });

        listBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/grid_layout_snap_small_stock-512_32x32.png"))); // NOI18N
        listBtn.setToolTipText("");

        jCheckBox1.setText("Two charts");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showYearDataCheckbox)
                            .addGroup(parametersPanelLayout.createSequentialGroup()
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(parametersPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yearLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(parametersPanelLayout.createSequentialGroup()
                                        .addComponent(startTimeLabel)
                                        .addGap(89, 89, 89)
                                        .addComponent(endTimeLabel))
                                    .addGroup(parametersPanelLayout.createSequentialGroup()
                                        .addComponent(startTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeIntervalLabel)
                                    .addComponent(timeIntervalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sportsChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sportsLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)))
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lineChartBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(histogramBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pieChartBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listBtn)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addComponent(showYearDataCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startTimeLabel)
                            .addComponent(endTimeLabel)
                            .addComponent(yearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sportsLabel)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sportsChooseBtn)
                            .addComponent(showBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                        .addComponent(timeIntervalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeIntervalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(yearCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineChartBtn)
                    .addComponent(histogramBtn)
                    .addComponent(pieChartBtn)
                    .addComponent(listBtn)))
        );

        visualizationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualization"));
        visualizationPanel.setLayout(new java.awt.GridLayout(1, 0));

        testPanel.setBackground(new java.awt.Color(255, 255, 255));
        testPanel.setLayout(new java.awt.GridLayout(1, 0));
        visualizationPanel.add(testPanel);

        comparisonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistics comparison"));

        candidateList.setModel(new javax.swing.AbstractListModel() {
            List<String> items = new ArrayList<>();
            public int getSize() { return items.size(); }
            public Object getElementAt(int i) { return items.get(i); }
            public void addAll(List<String> newItems){ items.addAll(newItems); }
            public void addElement(String item){ items.add(item);}
        });
        jScrollPane2.setViewportView(candidateList);

        eventList.setModel(new javax.swing.DefaultListModel() {
            List<String> items = new ArrayList<>();
            public int getSize() { return items.size(); }
            public Object getElementAt(int i) { return items.get(i); }
            public void addAll(List<String> newItems){ items.addAll(newItems); }
            public void addElement(String item){ items.add(item);}
        });
        jScrollPane1.setViewportView(eventList);

        sportComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "< -- >", "Football", "Hockey", "Tennis", "Skating", "Cycling", " " }));
        sportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportTypeChangedHandler(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Event", "Match", "Players", "Other" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comparisonTypeChangedHandler(evt);
            }
        });

        typeLabel.setText("Type");

        sportLabel2.setText("Sport");

        eventsLabel.setText("Events");

        Candidates.setText("Candidates");

        addEventBtn.setText("Add");
        addEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventBtnActionPerformed(evt);
            }
        });

        teamALabel.setText("TeamA");
        teamALabel.setEnabled(false);

        teamBComboBox.setEnabled(false);

        teamAComboBox.setEnabled(false);

        teamBLabel.setText("TeamB");
        teamBLabel.setEnabled(false);

        showComparisonBtn.setText("Show");
        showComparisonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showComparisonBtnActionPerformed(evt);
            }
        });

        clearCandidateBtn.setText("Clear all");
        clearCandidateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCandidateBtnActionPerformed(evt);
            }
        });

        showComparisonBtn1.setText("Show users");
        showComparisonBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showComparisonBtn1ActionPerformed(evt);
            }
        });

        deleteOneBtn.setText("Delete");
        deleteOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOneBtnActionPerformed(evt);
            }
        });

        addTeamBtn.setText("Add");
        addTeamBtn.setEnabled(false);
        addTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comparisonPanelLayout = new javax.swing.GroupLayout(comparisonPanel);
        comparisonPanel.setLayout(comparisonPanelLayout);
        comparisonPanelLayout.setHorizontalGroup(
            comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comparisonPanelLayout.createSequentialGroup()
                        .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(comparisonPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(sportLabel2))
                            .addComponent(sportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(teamALabel)
                        .addComponent(teamBLabel)
                        .addComponent(teamAComboBox, 0, 194, Short.MAX_VALUE)
                        .addComponent(teamBComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addTeamBtn))
                .addGap(18, 18, 18)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventsLabel)
                    .addGroup(comparisonPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEventBtn)))
                .addGap(18, 18, 18)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Candidates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comparisonPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showComparisonBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comparisonPanelLayout.createSequentialGroup()
                        .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearCandidateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteOneBtn)
                            .addComponent(showComparisonBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        comparisonPanelLayout.setVerticalGroup(
            comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comparisonPanelLayout.createSequentialGroup()
                        .addComponent(Candidates)
                        .addGap(179, 179, 179))
                    .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(comparisonPanelLayout.createSequentialGroup()
                            .addComponent(eventsLabel)
                            .addGap(179, 179, 179))
                        .addGroup(comparisonPanelLayout.createSequentialGroup()
                            .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(comparisonPanelLayout.createSequentialGroup()
                                    .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeLabel)
                                        .addComponent(sportLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamALabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(teamBLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addTeamBtn)
                                    .addGap(0, 23, Short.MAX_VALUE))
                                .addGroup(comparisonPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1)
                                        .addGroup(comparisonPanelLayout.createSequentialGroup()
                                            .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(addEventBtn)
                                                .addGroup(comparisonPanelLayout.createSequentialGroup()
                                                    .addComponent(deleteOneBtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(clearCandidateBtn)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(showComparisonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(showComparisonBtn1)))))
                            .addContainerGap()))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(comparisonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(comparisonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hockeyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hockeyCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hockeyCheckBoxActionPerformed

    private void sportsChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsChooseBtnActionPerformed
        // TODO add your handling code here:
        /*for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(false);
        }*/
        sportsDialog.setSize(380, 180);
        sportsDialog.show();
    }//GEN-LAST:event_sportsChooseBtnActionPerformed

    private void sportsOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsOKBtnActionPerformed
        // TODO add your handling code here:
        sportsDialog.dispose();
        
    }//GEN-LAST:event_sportsOKBtnActionPerformed

    private void sportsCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsCancelBtnActionPerformed
        // TODO add your handling code here:
        
        sportsDialog.dispose();
    }//GEN-LAST:event_sportsCancelBtnActionPerformed

    private void sportsSelectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsSelectAllBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(true);
        }
    }//GEN-LAST:event_sportsSelectAllBtnActionPerformed

    private void sportsDeselectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsDeselectAllBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(false);
        }
    }//GEN-LAST:event_sportsDeselectAllBtnActionPerformed

    private void sportsInverseSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsInverseSelectionBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(!cb.isSelected());
        }
    }//GEN-LAST:event_sportsInverseSelectionBtnActionPerformed

    private void showYearDataCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showYearDataCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showYearDataCheckboxActionPerformed

    private void yearDataCheckboxChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearDataCheckboxChanged
        // TODO add your handling code here:
        boolean showYear  = showYearDataCheckbox.isSelected();
        this.yearLabel.setEnabled(showYear);
        this.yearCombo.setEnabled(showYear);
        this.startTimeLabel.setEnabled(!showYear);
        this.endTimeLabel.setEnabled(!showYear);
        this.startTimePicker.setEnabled(!showYear);
        this.endTimePicker.setEnabled(!showYear);
    }//GEN-LAST:event_yearDataCheckboxChanged

    // If the show button is pressed we update the graph
    // 
    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        System.out.println("Pressed");
        setParameters();
        
        GraphInfo graphInfo = new GraphInfo(startTimePicker.getDate(),
                endTimePicker.getDate(), footballCheckBox.isSelected(),
            hockeyCheckBox.isSelected(), cyclingCheckBox.isSelected(),
            tennisCheckBox.isSelected(), skatingCheckBox.isSelected(), 1);
        fxPanel.drawScene(2);
    }//GEN-LAST:event_showBtnActionPerformed

    private void pieChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieChartBtnActionPerformed
        setParameters();
        PopFrame pf = new PopFrame(3);
        pf.setVisible(true);
        pf.toFront();
    }//GEN-LAST:event_pieChartBtnActionPerformed

    private void lineChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineChartBtnActionPerformed
        setParameters();
        PopFrame pf = new PopFrame(4);
        pf.setVisible(true);
        pf.toFront();
    }//GEN-LAST:event_lineChartBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void showComparisonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showComparisonBtnActionPerformed
        setParameters();
        List<String> candidates = getCandidates();
        SportData2.getInstance().setSelected(candidates);
        PopFrame pf = new PopFrame(5);
        pf.setVisible(true);
        pf.toFront();
    }//GEN-LAST:event_showComparisonBtnActionPerformed

    private void histogramBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramBtnActionPerformed
        setParameters();
        PopFrame pf = new PopFrame(5);
        pf.setVisible(true);
        pf.toFront();
    }//GEN-LAST:event_histogramBtnActionPerformed
    
    private void addEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventBtnActionPerformed
        // TODO add your handling code here:
        if(!eventList.isSelectionEmpty()){
            String newCandidate = eventList.getSelectedValue().toString();
            candidateListModel.addElement(newCandidate);
        }
    }//GEN-LAST:event_addEventBtnActionPerformed

    private void comparisonTypeChangedHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comparisonTypeChangedHandler
        // TODO add your handling code here:
        int type = typeComboBox.getSelectedIndex();
        if(type == 0 || type == 2 || type == 3){
            if(type == 2){
                eventsLabel.setText("Players");
            }else if(type == 0){
                eventsLabel.setText("Events");
            }else{
                eventsLabel.setText("Others");
            }
            teamALabel.setEnabled(false);
            teamBLabel.setEnabled(false);
            teamAComboBox.setEnabled(false);
            teamBComboBox.setEnabled(false);
            addTeamBtn.setEnabled(false);
            eventsLabel.setEnabled(true);
            eventList.setEnabled(true);
            addEventBtn.setEnabled(true);
        }else{
            teamALabel.setEnabled(true);
            teamBLabel.setEnabled(true);
            teamAComboBox.setEnabled(true);
            teamBComboBox.setEnabled(true);
            eventsLabel.setEnabled(false);
            eventList.setEnabled(false);
            addEventBtn.setEnabled(false);
            addTeamBtn.setEnabled(true);
        }
        
        sportChanged();
    }//GEN-LAST:event_comparisonTypeChangedHandler
    
    private void sportTypeChangedHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportTypeChangedHandler
        // TODO add your handling code here:
        sportChanged();
        
    }//GEN-LAST:event_sportTypeChangedHandler
    
    private void clearCandidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCandidateBtnActionPerformed
        // TODO add your handling code here:
        candidateListModel.clear();
    }//GEN-LAST:event_clearCandidateBtnActionPerformed

    private void showComparisonBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showComparisonBtn1ActionPerformed
        // TODO add your handling code here:
        setParameters();
        List<String> candidates = getCandidates();
        SportData2.getInstance().setSelected(candidates);
        PopFrame pf = new PopFrame(5);
        pf.setVisible(true);
        pf.toFront();
    }//GEN-LAST:event_showComparisonBtn1ActionPerformed

    private void deleteOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOneBtnActionPerformed
        // TODO add your handling code here:
        if(!candidateList.isSelectionEmpty()){
            candidateListModel.remove(candidateList.getSelectedIndex());
        }
    }//GEN-LAST:event_deleteOneBtnActionPerformed

    private void addTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamBtnActionPerformed
        // TODO add your handling code here:
        String teamA = teamAComboBox.getSelectedItem().toString();
        String teamB = teamBComboBox.getSelectedItem().toString();
        if(!(teamA.isEmpty() && teamB.isEmpty())){
            String newCandidate =  teamA + " vs " + teamB;   
            candidateListModel.addElement(newCandidate);
        }
    }//GEN-LAST:event_addTeamBtnActionPerformed
    
    private List<String> getCandidates(){
        List<String> candidates = new ArrayList<>();
        for(int i = 0; i < candidateListModel.size(); i++){
            String match = candidateListModel.getElementAt(i).toString().replaceAll("vs", ";&;");
            candidates.add(match);
            System.out.println(match);
        }
        return candidates;
    }
    
    public void sportChanged(){
        String sport = sportComboBox.getSelectedItem().toString().toLowerCase();
        eventListModel.clear();
        int type = typeComboBox.getSelectedIndex();
        if (type == 0) {
            List<String> events = SportData2.getInstance().getEvents(sport);
            for (String s : events) {
                eventListModel.addElement(s);
            }
        } else if(type == 2){
            List<String> players = SportData2.getInstance().getPlayers(sport);
            for (String p : players) {
                eventListModel.addElement(p);
            }
        }else if(type == 1){
            List<String> teams = SportData2.getInstance().getTeams(sport);
            teamAComboBox.removeAllItems();
            teamBComboBox.removeAllItems();
            for (String s : teams) {
                teamAComboBox.addItem(s);
                teamBComboBox.addItem(s);
            }
        }else{
            List<String> other = SportData2.getInstance().getOther(sport);
            for (String o : other) {
                eventListModel.addElement(o);
            }
        }
    }
    
    private void setParameters() {
        int timeInterval = 0;
        String selected = timeIntervalCombo.getSelectedItem().toString();
        switch (selected) {
            case "Month":
                timeInterval = 30;
                break;
            case "Week":
                timeInterval = 7;
                break;
            case "Day":
                timeInterval = 1;
                break;
        }
        
        SportData2.getInstance().setDates(getStartDate(), getEndDate());
        SportData2.getInstance().setSelected(getSports());
        SportData2.getInstance().setInterval(timeInterval);
        SportData2.getInstance().setFootballSeperate(jCheckBox1.isSelected());
    }
    
    private Date getStartDate() {
        return startTimePicker.getDate();
    }
    
    private Date getEndDate() {
        return endTimePicker.getDate();
    }
    
    private List<String> getSports() {
        List sports = new ArrayList();
        if(footballCheckBox.isSelected()) {
            sports.add(footballCheckBox.getText().toLowerCase());
        }
        if(hockeyCheckBox.isSelected()) {
            sports.add(hockeyCheckBox.getText().toLowerCase());
        }
        if(cyclingCheckBox.isSelected()) {
            sports.add(cyclingCheckBox.getText().toLowerCase());
        }
        if(tennisCheckBox.isSelected()) {
            sports.add(tennisCheckBox.getText().toLowerCase());
        }
        if(skatingCheckBox.isSelected()) {
            sports.add(skatingCheckBox.getText().toLowerCase());
        }
        return sports;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        SportData2.getInstance().init();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Candidates;
    private javax.swing.JButton addEventBtn;
    private javax.swing.JButton addTeamBtn;
    private javax.swing.JList candidateList;
    private javax.swing.JButton clearCandidateBtn;
    private javax.swing.JPanel comparisonPanel;
    private javax.swing.JCheckBox cyclingCheckBox;
    private javax.swing.JButton deleteOneBtn;
    private javax.swing.JLabel endTimeLabel;
    private com.lavantech.gui.comp.DateTimePicker endTimePicker;
    private javax.swing.JList eventList;
    private javax.swing.JLabel eventsLabel;
    private javax.swing.JCheckBox footballCheckBox;
    private javax.swing.JButton histogramBtn;
    private javax.swing.JCheckBox hockeyCheckBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lineChartBtn;
    private javax.swing.JButton listBtn;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JButton pieChartBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton showComparisonBtn;
    private javax.swing.JButton showComparisonBtn1;
    private javax.swing.JCheckBox showYearDataCheckbox;
    private javax.swing.JCheckBox skatingCheckBox;
    private javax.swing.JComboBox sportComboBox;
    private javax.swing.JLabel sportLabel2;
    private javax.swing.JButton sportsCancelBtn;
    private javax.swing.JButton sportsChooseBtn;
    private javax.swing.JButton sportsDeselectAllBtn;
    private javax.swing.JDialog sportsDialog;
    private javax.swing.JButton sportsInverseSelectionBtn;
    private javax.swing.JLabel sportsLabel;
    private javax.swing.JButton sportsOKBtn;
    private javax.swing.JButton sportsSelectAllBtn;
    private javax.swing.JLabel startTimeLabel;
    private com.lavantech.gui.comp.DateTimePicker startTimePicker;
    private javax.swing.JComboBox teamAComboBox;
    private javax.swing.JLabel teamALabel;
    private javax.swing.JComboBox teamBComboBox;
    private javax.swing.JLabel teamBLabel;
    private javax.swing.JCheckBox tennisCheckBox;
    private javax.swing.JPanel testPanel;
    private javax.swing.JComboBox timeIntervalCombo;
    private javax.swing.JLabel timeIntervalLabel;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel visualizationPanel;
    private javax.swing.JComboBox yearCombo;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
