/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dblis;

import gui.FXPanel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Chen
 */
public class NewMainFrame extends javax.swing.JFrame {
    private FXPanel fxPanel;

    /**
     * Creates new form NewMainFrame
     */
    List<JCheckBox> sportCheckboxes;
    public NewMainFrame() {
        initComponents();
        sportCheckboxes = new ArrayList<>();
        sportCheckboxes.add(hockyCheckBox);
        sportCheckboxes.add(tennisCheckBox);
        sportCheckboxes.add(footballCheckBox);
        sportCheckboxes.add(cyclyingCheckBox);
        sportCheckboxes.add(skatingCheckBox);
        fxPanel = new FXPanel();
        testPanel.add(fxPanel);
        fxPanel.drawScene(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sportsDialog = new javax.swing.JDialog();
        footballCheckBox = new javax.swing.JCheckBox();
        hockyCheckBox = new javax.swing.JCheckBox();
        cyclyingCheckBox = new javax.swing.JCheckBox();
        tennisCheckBox = new javax.swing.JCheckBox();
        skatingCheckBox = new javax.swing.JCheckBox();
        sportsSelectAllBtn = new javax.swing.JButton();
        sportsDeselectAllBtn = new javax.swing.JButton();
        sportsInverseSelectionBtn = new javax.swing.JButton();
        sportsOKBtn = new javax.swing.JButton();
        sportsCancelBtn = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        timeIntervalLabel = new javax.swing.JLabel();
        startTimePicker = new com.lavantech.gui.comp.DateTimePicker();
        endTimePicker = new com.lavantech.gui.comp.DateTimePicker();
        startTimeLabel = new javax.swing.JLabel();
        endTimeLabel = new javax.swing.JLabel();
        timeIntervalCombo = new javax.swing.JComboBox();
        sportsLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        yearLabel = new javax.swing.JLabel();
        sportsChooseBtn = new javax.swing.JButton();
        visualizationPanel = new javax.swing.JPanel();
        testPanel = new javax.swing.JPanel();

        sportsDialog.setTitle("Select the sports to show");

        footballCheckBox.setText("Football");

        hockyCheckBox.setText("Hockey");
        hockyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hockyCheckBoxActionPerformed(evt);
            }
        });

        cyclyingCheckBox.setText("Cyclying");

        tennisCheckBox.setText("Tennis");

        skatingCheckBox.setText("Skating");

        sportsSelectAllBtn.setText("Select all");
        sportsSelectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsSelectAllBtnActionPerformed(evt);
            }
        });

        sportsDeselectAllBtn.setText("Deselect all");
        sportsDeselectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsDeselectAllBtnActionPerformed(evt);
            }
        });

        sportsInverseSelectionBtn.setText("Invert selection");
        sportsInverseSelectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsInverseSelectionBtnActionPerformed(evt);
            }
        });

        sportsOKBtn.setText("OK");
        sportsOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsOKBtnActionPerformed(evt);
            }
        });

        sportsCancelBtn.setText("Cancel");
        sportsCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sportsDialogLayout = new javax.swing.GroupLayout(sportsDialog.getContentPane());
        sportsDialog.getContentPane().setLayout(sportsDialogLayout);
        sportsDialogLayout.setHorizontalGroup(
            sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sportsDialogLayout.createSequentialGroup()
                        .addComponent(footballCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hockyCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyclyingCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tennisCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skatingCheckBox))
                    .addGroup(sportsDialogLayout.createSequentialGroup()
                        .addComponent(sportsSelectAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sportsDeselectAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sportsInverseSelectionBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sportsOKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sportsCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sportsDialogLayout.setVerticalGroup(
            sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footballCheckBox)
                    .addComponent(hockyCheckBox)
                    .addComponent(cyclyingCheckBox)
                    .addComponent(tennisCheckBox)
                    .addComponent(skatingCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sportsDeselectAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(sportsSelectAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sportsInverseSelectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sportsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportsOKBtn)
                    .addComponent(sportsCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("That bird is fit");

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        timeIntervalLabel.setText("Time interval");

        startTimeLabel.setText("Start time");

        endTimeLabel.setText("End time");

        timeIntervalCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Week" }));

        sportsLabel.setText("Sports");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", " " }));

        yearLabel.setText("Year");

        sportsChooseBtn.setText("Choose");
        sportsChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsChooseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addComponent(startTimeLabel)
                        .addGap(89, 89, 89)
                        .addComponent(endTimeLabel))
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addComponent(startTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(yearLabel))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sportsLabel)
                    .addComponent(sportsChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeIntervalLabel)
                    .addComponent(timeIntervalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startTimeLabel)
                            .addComponent(endTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sportsLabel)
                            .addComponent(timeIntervalLabel)
                            .addComponent(yearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeIntervalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sportsChooseBtn))))
                .addContainerGap())
        );

        visualizationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualization"));

        testPanel.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout visualizationPanelLayout = new javax.swing.GroupLayout(visualizationPanel);
        visualizationPanel.setLayout(visualizationPanelLayout);
        visualizationPanelLayout.setHorizontalGroup(
            visualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizationPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(testPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        visualizationPanelLayout.setVerticalGroup(
            visualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizationPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(testPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualizationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parametersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hockyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hockyCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hockyCheckBoxActionPerformed

    private void sportsChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsChooseBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(false);
        }
        sportsDialog.setSize(380, 180);
        sportsDialog.show();
    }//GEN-LAST:event_sportsChooseBtnActionPerformed

    private void sportsOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsOKBtnActionPerformed
        // TODO add your handling code here:
        sportsDialog.dispose();
        
    }//GEN-LAST:event_sportsOKBtnActionPerformed

    private void sportsCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsCancelBtnActionPerformed
        // TODO add your handling code here:
        
        sportsDialog.dispose();
    }//GEN-LAST:event_sportsCancelBtnActionPerformed

    private void sportsSelectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsSelectAllBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(true);
        }
    }//GEN-LAST:event_sportsSelectAllBtnActionPerformed

    private void sportsDeselectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsDeselectAllBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(false);
        }
    }//GEN-LAST:event_sportsDeselectAllBtnActionPerformed

    private void sportsInverseSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsInverseSelectionBtnActionPerformed
        // TODO add your handling code here:
        for(JCheckBox cb : sportCheckboxes){
            cb.setSelected(!cb.isSelected());
        }
    }//GEN-LAST:event_sportsInverseSelectionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cyclyingCheckBox;
    private javax.swing.JLabel endTimeLabel;
    private com.lavantech.gui.comp.DateTimePicker endTimePicker;
    private javax.swing.JCheckBox footballCheckBox;
    private javax.swing.JCheckBox hockyCheckBox;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JCheckBox skatingCheckBox;
    private javax.swing.JButton sportsCancelBtn;
    private javax.swing.JButton sportsChooseBtn;
    private javax.swing.JButton sportsDeselectAllBtn;
    private javax.swing.JDialog sportsDialog;
    private javax.swing.JButton sportsInverseSelectionBtn;
    private javax.swing.JLabel sportsLabel;
    private javax.swing.JButton sportsOKBtn;
    private javax.swing.JButton sportsSelectAllBtn;
    private javax.swing.JLabel startTimeLabel;
    private com.lavantech.gui.comp.DateTimePicker startTimePicker;
    private javax.swing.JCheckBox tennisCheckBox;
    private javax.swing.JPanel testPanel;
    private javax.swing.JComboBox timeIntervalCombo;
    private javax.swing.JLabel timeIntervalLabel;
    private javax.swing.JPanel visualizationPanel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
